# Generated by Django 4.2.3 on 2023-07-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manager', '0002_alter_user_idname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idname',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
